services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - heartbeat-network

  manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HEARTBEAT_TIMEOUT=15
    command: ["uvicorn", "manager:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - heartbeat-network

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - WORKER_NAME=FastAPI Worker 1
      - WORKER_PORT=8001
      - MANAGER_HOST=manager
      - MANAGER_PORT=8000
      - HEARTBEAT_INTERVAL=5
    command: ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8001"]
    depends_on:
      - manager
    networks:
      - heartbeat-network

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8001"
    environment:
      - WORKER_NAME=FastAPI Worker 2
      - WORKER_PORT=8001
      - MANAGER_HOST=manager
      - MANAGER_PORT=8000
      - HEARTBEAT_INTERVAL=5
    command: ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8001"]
    depends_on:
      - manager
    networks:
      - heartbeat-network

networks:
  heartbeat-network:
    driver: bridge

